In [ ]:
# ----------------------------------------------------------
# Preprocesamiento de Datos
# Competencia AI4Eng 2025
# Integrantes: Liset Pérez-Monica Del Castillo
# Programa: Ingeniería Industrial
# ----------------------------------------------------------

# Importar las librerías necesarias

import pandas as pd
import numpy as np
import sklearn as skl
import os

In [ ]:
#Importamos los archivos necesarios

In [ ]:
os.environ['KAGGLE_CONFIG_DIR']="."

In [ ]:
!kaggle competitions download -c udea-ai-4-eng-20252-pruebas-saber-pro-colombia

In [ ]:
!unzip udea-ai-4-eng-20252-pruebas-saber-pro-colombia.zip

Archive:  udea-ai-4-eng-20252-pruebas-saber-pro-colombia.zip
replace submission_example.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename:

In [ ]:
df = pd.read_csv('train.csv')
df

,ID,PERIODO_ACADEMICO,E_PRGM_ACADEMICO,E_PRGM_DEPARTAMENTO,E_VALORMATRICULAUNIVERSIDAD,E_HORASSEMANATRABAJA,F_ESTRATOVIVIENDA,F_TIENEINTERNET,F_EDUCACIONPADRE,F_TIENELAVADORA,...,E_PRIVADO_LIBERTAD,E_PAGOMATRICULAPROPIO,F_TIENECOMPUTADOR,F_TIENEINTERNET.1,F_EDUCACIONMADRE,RENDIMIENTO_GLOBAL,INDICADOR_1,INDICADOR_2,INDICADOR_3,INDICADOR_4
0,904256,20212,ENFERMERIA,BOGOTÁ,Entre 5.5 millones y menos de 7 millones,Menos de 10 horas,Estrato 3,Si,Técnica o tecnológica incompleta,Si,...,N,No,Si,Si,Postgrado,medio-alto,0.322,0.208,0.310,0.267
1,645256,20212,DERECHO,ATLANTICO,Entre 2.5 millones y menos de 4 millones,0,Estrato 3,No,Técnica o tecnológica completa,Si,...,N,No,Si,No,Técnica o tecnológica incompleta,bajo,0.311,0.215,0.292,0.264
2,308367,20203,MERCADEO Y PUBLICIDAD,BOGOTÁ,Entre 2.5 millones y menos de 4 millones,Más de 30 horas,Estrato 3,Si,Secundaria (Bachillerato) completa,Si,...,N,No,No,Si,Secundaria (Bachillerato) completa,bajo,0.297,0.214,0.305,0.264
3,470353,20195,ADMINISTRACION DE EMPRESAS,SANTANDER,Entre 4 millones y menos de 5.5 millones,0,Estrato 4,Si,No sabe,Si,...,N,No,Si,Si,Secundaria (Bachillerato) completa,alto,0.485,0.172,0.252,0.190
4,989032,20212,PSICOLOGIA,ANTIOQUIA,Entre 2.5 millones y menos de 4 millones,Entre 21 y 30 horas,Estrato 3,Si,Primaria completa,Si,...,N,No,Si,Si,Primaria completa,medio-bajo,0.316,0.232,0.285,0.294
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
692495,25096,20195,BIOLOGIA,LA GUAJIRA,Entre 500 mil y menos de 1 millón,Entre 11 y 20 horas,Estrato 2,Si,Secundaria (Bachillerato) completa,Si,...,N,Si,Si,Si,Secundaria (Bachillerato) incompleta,medio-alto,0.237,0.271,0.271,0.311
692496,754213,20212,PSICOLOGIA,NORTE SANTANDER,Entre 2.5 millones y menos de 4 millones,Más de 30 horas,Estrato 3,Si,Primaria incompleta,Si,...,N,No,Si,Si,Secundaria (Bachillerato) incompleta,bajo,0.314,0.240,0.278,0.260
692497,504185,20183,ADMINISTRACIÓN EN SALUD OCUPACIONAL,BOGOTÁ,Entre 1 millón y menos de 2.5 millones,Menos de 10 horas,Estrato 3,Si,Secundaria (Bachillerato) completa,Si,...,N,Si,Si,Si,Secundaria (Bachillerato) incompleta,medio-bajo,0.286,0.240,0.314,0.287
692498,986620,20195,PSICOLOGIA,TOLIMA,Entre 2.5 millones y menos de 4 millones,Menos de 10 horas,Estrato 1,No,Primaria completa,No,...,N,Si,Si,No,Primaria completa,bajo,0.132,0.426,0.261,0.328
692499,933374,20195,PSICOLOGIA,ANTIOQUIA,Entre 5.5 millones y menos de 7 millones,Más de 30 horas,Estrato 4,Si,Secundaria (Bachillerato) completa,Si,...,N,No,Si,Si,Técnica o tecnológica completa,alto,0.487,0.180,0.251,0.187

In [ ]:
#convertimos los valores de la columna E_VALORMATRICULAUNIVERSIDAD a valores numéricos, para que nos dé el promedio de los mismos

def convertir_valor_matricula(valor):
    if pd.isna(valor):
        return np.nan
    elif 'Menos de 500 mil' in valor:
        return 250000  # Asignamos un valor promedio entre 0 y 500 mil
    elif 'Entre 500 mil y menos de 1 millón' in valor:
        return 750000  # Promedio entre 500 mil y 1 millón
    elif 'Entre 1 millón y menos de 2.5 millones' in valor:
        return 1750000  # Promedio entre 1 y 2.5 millones
    elif 'Entre 2.5 millones y menos de 4 millones' in valor:
        return 3250000  # Promedio entre 2.5 y 4 millones
    elif 'Entre 4 millones y menos de 5.5 millones' in valor:
        return 4750000  # Promedio entre 4 y 5.5 millones
    elif 'Entre 5.5 millones y menos de 7 millones' in valor:
        return 6250000  # Promedio entre 5.5 y 7 millones
    elif 'Más de 7 millones' in valor:
        return 7500000  # Asignamos un valor mínimo representativo superior a 7 millones
    elif 'No pagó matrícula' in valor:
        return 0  # Asumimos que no se pagó nada
    else:
        return np.nan  # Para cualquier caso que no coincida

In [ ]:
df_copy = df.copy()
df_copy['E_VALORMATRICULAUNIVERSIDAD'] = df_copy['E_VALORMATRICULAUNIVERSIDAD'].apply(convertir_valor_matricula)

media = df_copy ['E_VALORMATRICULAUNIVERSIDAD'].mean()
df_copy['E_VALORMATRICULAUNIVERSIDAD'] = df_copy['E_VALORMATRICULAUNIVERSIDAD'].fillna(media.round(3))

df_copy['E_VALORMATRICULAUNIVERSIDAD'].unique() # Se verifica que ya no queden valores nulos en la columna E_VALORMATRICULAUNIVERSIDAD

array([6250000.   , 3250000.   , 4750000.   , 7500000.   , 1750000.   ,
        750000.   ,  250000.   ,       0.   , 2815800.269])

# Se define la función para convertir los valores de ESTU_HORASSEMANATRABAJA en datos numéricos.

In [ ]:
#convertimos los valores de la columna E_HORASSEMANATRABAJA a valores numéricos,
def convertir_horas_trabajadas(valor):
    if isinstance(valor, str):
        if "Entre" in valor:
            partes = valor.split('y')
            min_val = float(partes[0].split(' ')[-2])  # Obtener el penúltimo elemento
            max_val = float(partes[1].split(' ')[-2])  # Obtener el penúltimo elemento de la segunda parte
            return (min_val + max_val) / 2  # Retornar el promedio del rango

        elif "Más de" in valor:
            return float(valor.split(' ')[2])  # Convertir a número

        elif "Menos de" in valor:
            return float(valor.split(' ')[2])  # Convertir a número

        elif "0" in valor:
            return 0  # Devolver 0 en número

    return np.nan  # Devolver NaN si no es un valor válido

In [ ]:
# Applicamos la conversión y eliminamos los valores nulos para la columna E_HORASSEMANATRABAJA

df_copy['E_HORASSEMANATRABAJA'] = df_copy['E_HORASSEMANATRABAJA'].apply(convertir_horas_trabajadas)

df_copy['E_HORASSEMANATRABAJA'] = df_copy['E_HORASSEMANATRABAJA'].fillna(0)

df_copy['E_HORASSEMANATRABAJA'].unique() # Se verifica que ya no queden valores nulos en la columna ESTU_HORASSEMANATRABAJA

array([10. ,  0. , 30. , 25.5, 15.5])

In [ ]:
#Creamos un diccionario para la correspondiente F_ESTRATOVIVIENDA y se hacen los reemplazos necesarios

estrato_dict = {
    'Estrato 1': 1,
    'Estrato 2': 2,
    'Estrato 3': 3,
    'Estrato 4': 4,
    'Estrato 5': 5,
    'Estrato 6': 6,
    'Sin Estrato': 0,
    np.nan: 0  # Cambiar nan a 0
}

df_copy['F_ESTRATOVIVIENDA'] = df_copy['F_ESTRATOVIVIENDA'].replace(estrato_dict)

df_copy['F_ESTRATOVIVIENDA'].unique() # Se verifica que ya no queden valores nulos en la columna FAMI_ESTRATOVIVIENDA

/tmp/ipython-input-3748423860.py:14: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_copy['F_ESTRATOVIVIENDA'] = df_copy['F_ESTRATOVIVIENDA'].replace(estrato_dict)

array([3., 4., 5., 2., 1., 0., 6.])

In [ ]:
# Comenzamos con la conversión a binomiales, anulamos los valores nulos para E_PAGOMATRICULAPROPIO
df_copy['E_PAGOMATRICULAPROPIO'] = df_copy['E_PAGOMATRICULAPROPIO'].replace({'Si': 1, 'No': 0})

df_copy['E_PAGOMATRICULAPROPIO'] = df_copy['E_PAGOMATRICULAPROPIO'].fillna(0)

df_copy['E_PAGOMATRICULAPROPIO'].unique() # Se verifica que ya no queden valores nulos en la columna E_PAGOMATRICULAPROPIO

/tmp/ipython-input-1134029491.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_copy['E_PAGOMATRICULAPROPIO'] = df_copy['E_PAGOMATRICULAPROPIO'].replace({'Si': 1, 'No': 0})

array([0., 1.])

In [ ]:
#Usamos un segundo diccionario para la columna RENDIMIENTO_GLOBAL que es nuestro objetivo, asignando la clasificiación en orden de aumento

rend_dict = {
    'bajo': 1,
    'medio-bajo': 2,
    'medio-alto': 3,
    'alto': 4,
}

df_copy['RENDIMIENTO_GLOBAL'] = df_copy['RENDIMIENTO_GLOBAL'].replace(rend_dict)

df_copy['RENDIMIENTO_GLOBAL'].unique() # Se verifica que ya no queden valores nulos en la columna RENDIMIENTO_GLOBAL

/tmp/ipython-input-3679978848.py:10: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_copy['RENDIMIENTO_GLOBAL'] = df_copy['RENDIMIENTO_GLOBAL'].replace(rend_dict)

array([3, 1, 4, 2])

In [ ]:
df_copy['F_TIENEINTERNET.1'] = df_copy['F_TIENEINTERNET'].replace({'Si': 1, 'No': 0})

df_copy['F_TIENEINTERNET.1'] = df_copy['F_TIENEINTERNET.1'].fillna(0)

df_copy = df_copy.drop('F_TIENEINTERNET', axis=1) # Drop the original string column

df_copy['F_TIENEINTERNET.1'].unique() # Se verifica que ya no queden valores nulos en la columna F_TIENEINTERNET.1

/tmp/ipython-input-2931566653.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_copy['F_TIENEINTERNET.1'] = df_copy['F_TIENEINTERNET'].replace({'Si': 1, 'No': 0})

array([1., 0.])

In [ ]:
def to_onehot(x):
    values = np.unique(x)
    r = np.r_[[np.argwhere(i==values)[0][0] for i in x]]
    return np.eye(len(values))[r].astype(int)

def replace_column_with_onehot(d, col):
    assert sum(d[col].isna())==0, "column must have no NaN values"
    values = np.unique(d[col]
                      )
    k = to_onehot(d[col].values)
    r = pd.DataFrame(k, columns=["%s_%s"%(col, values[i]) for i in range(k.shape[1])], index=d.index).join(d)
    del(r[col])
    return r

In [ ]:
col_m = 'F_EDUCACIONMADRE'
df_copy[col_m].fillna('No Aplica', inplace=True)
madre_onehot = replace_column_with_onehot(df_copy[[col_m]], col_m)
df_copy = df_copy.join(madre_onehot)
df_copy = df_copy.drop(col_m, axis=1)

col_p = 'F_EDUCACIONPADRE'
df_copy[col_p].fillna('No Aplica', inplace=True)
padre_onehot = replace_column_with_onehot(df_copy[[col_p]], col_p)
df_copy = df_copy.join(padre_onehot)
df_copy = df_copy.drop(col_p, axis=1)

df_copy

/tmp/ipython-input-678676079.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_copy[col_m].fillna('No Aplica', inplace=True)
/tmp/ipython-input-678676079.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_copy[col_p].fillna('No Aplica', inplace=True)

,ID,PERIODO_ACADEMICO,E_PRGM_ACADEMICO,E_PRGM_DEPARTAMENTO,E_VALORMATRICULAUNIVERSIDAD,E_HORASSEMANATRABAJA,F_ESTRATOVIVIENDA,F_TIENELAVADORA,F_TIENEAUTOMOVIL,E_PRIVADO_LIBERTAD,...,F_EDUCACIONPADRE_Ninguno,F_EDUCACIONPADRE_No Aplica,F_EDUCACIONPADRE_No sabe,F_EDUCACIONPADRE_Postgrado,F_EDUCACIONPADRE_Primaria completa,F_EDUCACIONPADRE_Primaria incompleta,F_EDUCACIONPADRE_Secundaria (Bachillerato) completa,F_EDUCACIONPADRE_Secundaria (Bachillerato) incompleta,F_EDUCACIONPADRE_Técnica o tecnológica completa,F_EDUCACIONPADRE_Técnica o tecnológica incompleta
0,904256,20212,ENFERMERIA,BOGOTÁ,6250000.0,10.0,3.0,Si,Si,N,...,0,0,0,0,0,0,0,0,0,1
1,645256,20212,DERECHO,ATLANTICO,3250000.0,0.0,3.0,Si,No,N,...,0,0,0,0,0,0,0,0,1,0
2,308367,20203,MERCADEO Y PUBLICIDAD,BOGOTÁ,3250000.0,30.0,3.0,Si,No,N,...,0,0,0,0,0,0,1,0,0,0
3,470353,20195,ADMINISTRACION DE EMPRESAS,SANTANDER,4750000.0,0.0,4.0,Si,No,N,...,0,0,1,0,0,0,0,0,0,0
4,989032,20212,PSICOLOGIA,ANTIOQUIA,3250000.0,25.5,3.0,Si,Si,N,...,0,0,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
692495,25096,20195,BIOLOGIA,LA GUAJIRA,750000.0,15.5,2.0,Si,No,N,...,0,0,0,0,0,0,1,0,0,0
692496,754213,20212,PSICOLOGIA,NORTE SANTANDER,3250000.0,30.0,3.0,Si,No,N,...,0,0,0,0,0,1,0,0,0,0
692497,504185,20183,ADMINISTRACIÓN EN SALUD OCUPACIONAL,BOGOTÁ,1750000.0,10.0,3.0,Si,No,N,...,0,0,0,0,0,0,1,0,0,0
692498,986620,20195,PSICOLOGIA,TOLIMA,3250000.0,10.0,1.0,No,No,N,...,0,0,0,0,1,0,0,0,0,0
692499,933374,20195,PSICOLOGIA,ANTIOQUIA,6250000.0,30.0,4.0,Si,Si,N,...,0,0,0,0,0,0,1,0,0,0

In [ ]:
# Eliminamos dos columnas
df_copy = df_copy.drop(['E_PRGM_ACADEMICO'], axis=1, errors='ignore')
df_copy = df_copy.drop(['PERIODO_ACADEMICO'], axis=1, errors='ignore')
df_copy = df_copy.drop(['E_PRGM_DEPARTAMENTO'], axis=1, errors='ignore')

df_copy

,ID,E_VALORMATRICULAUNIVERSIDAD,E_HORASSEMANATRABAJA,F_ESTRATOVIVIENDA,F_TIENELAVADORA,F_TIENEAUTOMOVIL,E_PRIVADO_LIBERTAD,E_PAGOMATRICULAPROPIO,F_TIENECOMPUTADOR,F_TIENEINTERNET.1,...,F_EDUCACIONPADRE_Ninguno,F_EDUCACIONPADRE_No Aplica,F_EDUCACIONPADRE_No sabe,F_EDUCACIONPADRE_Postgrado,F_EDUCACIONPADRE_Primaria completa,F_EDUCACIONPADRE_Primaria incompleta,F_EDUCACIONPADRE_Secundaria (Bachillerato) completa,F_EDUCACIONPADRE_Secundaria (Bachillerato) incompleta,F_EDUCACIONPADRE_Técnica o tecnológica completa,F_EDUCACIONPADRE_Técnica o tecnológica incompleta
0,904256,6250000.0,10.0,3.0,Si,Si,N,0.0,Si,1.0,...,0,0,0,0,0,0,0,0,0,1
1,645256,3250000.0,0.0,3.0,Si,No,N,0.0,Si,0.0,...,0,0,0,0,0,0,0,0,1,0
2,308367,3250000.0,30.0,3.0,Si,No,N,0.0,No,1.0,...,0,0,0,0,0,0,1,0,0,0
3,470353,4750000.0,0.0,4.0,Si,No,N,0.0,Si,1.0,...,0,0,1,0,0,0,0,0,0,0
4,989032,3250000.0,25.5,3.0,Si,Si,N,0.0,Si,1.0,...,0,0,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
692495,25096,750000.0,15.5,2.0,Si,No,N,1.0,Si,1.0,...,0,0,0,0,0,0,1,0,0,0
692496,754213,3250000.0,30.0,3.0,Si,No,N,0.0,Si,1.0,...,0,0,0,0,0,1,0,0,0,0
692497,504185,1750000.0,10.0,3.0,Si,No,N,1.0,Si,1.0,...,0,0,0,0,0,0,1,0,0,0
692498,986620,3250000.0,10.0,1.0,No,No,N,1.0,Si,0.0,...,0,0,0,0,1,0,0,0,0,0
692499,933374,6250000.0,30.0,4.0,Si,Si,N,0.0,Si,1.0,...,0,0,0,0,0,0,1,0,0,0

In [ ]:
X_train = df_copy.drop(['RENDIMIENTO_GLOBAL', 'ID'], axis=1)
y_train = df_copy['RENDIMIENTO_GLOBAL']

In [ ]:
#Entrenamiento para RandomForestClassifier
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestClassifier

# Convert remaining string columns to numerical
# Assuming 'Si': 1, 'No': 0 for boolean-like features
boolean_cols_to_convert = ['F_TIENELAVADORA', 'F_TIENEAUTOMOVIL', 'F_TIENECOMPUTADOR'] # Corrected typo here
for col in boolean_cols_to_convert:
    if col in X_train.columns:
        X_train[col] = X_train[col].replace({'Si': 1, 'No': 0}).fillna(0)

# Convert 'E_PRIVADO_LIBERTAD' (assuming 'N': 0, 'S': 1)
if 'E_PRIVADO_LIBERTAD' in X_train.columns:
    X_train['E_PRIVADO_LIBERTAD'] = X_train['E_PRIVADO_LIBERTAD'].replace({'N': 0, 'S': 1}).fillna(0)

model = Pipeline(steps=[('clasifier', RandomForestClassifier(random_state=42))])
model.fit(X_train, y_train)

/tmp/ipython-input-491084612.py:10: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  X_train[col] = X_train[col].replace({'Si': 1, 'No': 0}).fillna(0)
/tmp/ipython-input-491084612.py:14: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  X_train['E_PRIVADO_LIBERTAD'] = X_train['E_PRIVADO_LIBERTAD'].replace({'N': 0, 'S': 1}).fillna(0)

Pipeline(steps=[('clasifier', RandomForestClassifier(random_state=42))])

In [ ]:
from sklearn.metrics import accuracy_score

y_val_pred = model.predict(X_train)
accuracy = accuracy_score(y_train, y_val_pred)
print("Accuracy:", accuracy)

Accuracy: 0.9999971119133574

In [ ]:
df_test = pd.read_csv('data/test.csv')
df_test

FileNotFoundError: [Errno 2] No such file or directory: 'data/test.csv'

In [ ]:
df_test_copy = df_test.copy()
df_test_copy['E_VALORMATRICULAUNIVERSIDAD'] = df_test_copy['E_VALORMATRICULAUNIVERSIDAD'].apply(convertir_valor_matricula)

media = df_test_copy ['E_VALORMATRICULAUNIVERSIDAD'].mean()
df_test_copy['E_VALORMATRICULAUNIVERSIDAD'] = df_test_copy['E_VALORMATRICULAUNIVERSIDAD'].fillna(media.round(3))

df_test_copy['E_VALORMATRICULAUNIVERSIDAD'].unique()

In [ ]:
df_test_copy['F_TIENEINTERNET'] = df_test_copy['F_TIENEINTERNET'].replace({'Si': 1, 'No': 0})

df_test_copy['F_TIENEINTERNET'] = df_test_copy['F_TIENEINTERNET'].fillna(0)

df_test_copy['F_TIENEINTERNET'].unique()

In [ ]:
df_test_copy['E_HORASSEMANATRABAJA'] = df_test_copy['E_HORASSEMANATRABAJA'].apply(convertir_horas_trabajadas)

df_test_copy['E_HORASSEMANATRABAJA'] = df_test_copy['E_HORASSEMANATRABAJA'].fillna(0)

df_test_copy['E_HORASSEMANATRABAJA'].unique()

In [ ]:
df_test_copy['F_ESTRATOVIVIENDA'] = df_test_copy['F_ESTRATOVIVIENDA'].replace(estrato_dict)

df_test_copy['F_ESTRATOVIVIENDA'].unique()

In [ ]:
df_test_copy['E_PAGOMATRICULAPROPIO'] = df_test_copy['E_PAGOMATRICULAPROPIO'].replace({'Si': 1, 'No': 0})

df_test_copy['E_PAGOMATRICULAPROPIO'] = df_test_copy['E_PAGOMATRICULAPROPIO'].fillna(0)

df_test_copy['E_PAGOMATRICULAPROPIO'].unique()

In [ ]:
col_m = 'F_EDUCACIONMADRE'
df_test_copy[col_m].fillna('No Aplica', inplace=True)
madre_onehot = replace_column_with_onehot(df_test_copy[[col_m]], col_m)
df_test_copy = df_test_copy.join(madre_onehot)
df_test_copy = df_test_copy.drop(col_m, axis=1)

col_p = 'F_EDUCACIONPADRE'
df_test_copy[col_p].fillna('No Aplica', inplace=True)
padre_onehot = replace_column_with_onehot(df_test_copy[[col_p]], col_p)
df_test_copy = df_test_copy.join(padre_onehot)
df_test_copy = df_test_copy.drop(col_p, axis=1)

df_test_copy

In [ ]:
X_test = df_test_copy.drop(['ID'], axis=1)
Y_test_pred = model.predict(X_test)

In [ ]:
Y_test_pred_series = pd.Series(Y_test_pred)

rend_dict_rev = {
    1: 'bajo',
    2: 'medio-bajo',
    3: 'medio-alto',
    4: 'alto',
}

submission = pd.DataFrame({
    'ID': df_test['ID'],
    'RENDIMIENTO_GLOBAL': Y_test_pred_series.replace(rend_dict_rev)
})

submission.to_csv('submission.csv', index=False)